### PR TITLE
Remove prompts and outputs from copy

### PR DESCRIPTION
**Pull request by thoo**
Related to #18

### CODE REVIEW

**Comment by thoo** [comment]
I see. I am going to close it. Btw, scikit-image had integrated your ext in dev. 👍

**Comment by choldgraf** [comment]
ah ok - to be clear, I can definitely see the value in something like this...but I'm wondering if we want to hard-code those values into sphinx-gallery, or if it could be something configurable in `conf.py` or something like this.

Another option is that we could provide some short documentation on javascript people can add to their sites in order to remove certain parts of the code cell before the "copy" happens...similar to here https://sphinx-copybutton.readthedocs.io/en/latest/#use-a-different-copy-button-image

what do you think?

**Comment by choldgraf** [comment]
@thoo see #21 for some thoughts on how to add configuration options - I think this would be a nice addition if we could

1. Keep everything in the code cells copied by default
2. Expose the ability for people to add configuration for specific tags that would then trigger your "don't copy code with these tags" function

**Comment by thoo** [comment]
That is very nice. I would say not many people will have issues with `prompt >>>` or `output`. Configuration file would be a great improvement. 👍

**Pull request closed without merging**
